# Experiment settings
# Experiment settings
base_config: neumeta/config/base_config.yaml
# Model configurations
model:
  type: ResNet56
  pretrained_path: neumeta/pretrained_models/cifar100_ResNet56-smoothed.pt
  num_param: 8
  smooth: False
  fuse: False
  bottom_up: True
  single_block: False

experiment:
  name: TEST
  debug: True
  num_epochs: 1
  log_interval: 25
  eval_interval: 1
  arch_accumulation_steps: 1
  batch_accumulation_steps: 4
  iterative: True
  custom_init: True


# Training configurations
training:
  learning_rate: 0.00085
  eta_min: 0.00085
  ft_scaling: False
  ft_scalinigFactor: 0.1
  batch_size: 128
  coordinate_noise: 1.0
  scheduler: cosine
  T_max: ${experiment.num_epochs}
  # strong_aug: v1
  weight_decay: 1e-4
  clip_grad: 10.0
  save_model_path: experiments/${experiment.name} # Directory to save the trained model

# Hyper-model specifications (specific to NeRF)
hyper_model:
  type: hierarchical_resmlpDict
  kernel_groups: 4
  input_dim: 6
  hidden_dim: 512
  num_layers: 8
  num_freqs: 32
  output_dim: 9
  scalar: 0.1
  use_ema: True
  extend_ema: True
  ema_decay: 0.995  # Exponential moving average decay

  loss_weight:
    ce_weight: 100.0
    reg_weight: 0.001
    recon_weight: 1.0
    kd_weight: 0.1


# Experiment dimensions configuration
dimensions:
  range: [32, 64]  # Dimension range for the experiment
  test: 32  # Testing dimension
  norm: 64  # Normalization factor
  start: 64  # Starting dimension
