base_config: neumeta/config/base_config.yaml
# Model configurations
model:
  type: ResNet56
  pretrained_path: neumeta/pretrained_models/cifar100_ResNet56-smoothed.pt
  num_param: 1 #Learnable Blocks
  bottom_up: True
  smooth: False
  fuse: False
  single_block: False
  
# Experiment settings
experiment:
  name: Block0_CentralValue_recWeight_${experiment.batch_accumulation_steps}AccumulationSteps_CustomInit:${experiment.custom_init}_singleBlock:${model.single_block}_${experiment.num_epochs}e_lr${training.learning_rate}_ftScaling:${training.ft_scaling}:${training.ft_scalinigFactor}
  debug: False
  num_epochs: 200
  log_interval: 26
  eval_interval: 10
  arch_accumulation_steps: 1
  batch_accumulation_steps: 1
  iterative: True
  custom_init: True

# Training configurations
training:
  batch_size: 128
  learning_rate: 3e-4
  eta_min: 3e-5
  scheduler: cosine
  warmup_epochs: 10
  T_max: ${experiment.num_epochs}
  weight_decay: 1e-4
  coordinate_noise: 1.0
  clip_grad: 10.0
  ft_scaling: True
  ft_scalinigFactor: 0.1
  save_model_path: /work/tesi_tsommariva/experiments/AaITERATIVE/${experiment.name} # Directory to save the trained model

# Hyper-model specifications (specific to NeRF)
hyper_model:
  type: resmlp
  input_dim: 6
  hidden_dim: 512
  num_layers: 8
  num_freqs: 32
  output_dim: 9
  ema_decay: 0.995  # Exponential moving average decay

  loss_weight:
    ce_weight: 100.0
    reg_weight: 0.001
    recon_weight: 1.0
    kd_weight: 0.1


# Experiment dimensions configuration
dimensions:
  range: [32, 64]  # Dimension range for the experiment
  test_range: [16, 64]  # Dimension range for testing
  test: 32  # Testing dimension
  norm: 64  # Normalization factor
  start: 64  # Starting dimension