wandb_version: 1

experiment:
  desc: null
  value: '{''name'': ''ninr_resnet20_cifar10_32-64-4layer-60e-noisecoord-resmlpv2_smooth'',
    ''recononly'': 0, ''num_epochs'': 60, ''log_interval'': 250, ''eval_interval'':
    1, ''seed'': 42}'
model:
  desc: null
  value: '{''type'': ''ResNet20'', ''pretrained_path'': ''/homes/tsommariva/neumeta/neumeta/pretrained_models/cifar10_resnet20-4118986f.pt'',
    ''smooth'': True}'
training:
  desc: null
  value: '{''learning_rate'': 0.001, ''batch_size'': 64, ''coordinate_noise'': 1.0,
    ''lr_steps'': [100, 150], ''weight_decay'': 0.01, ''clip_grad'': 10.0, ''save_model_path'':
    ''experiments/resnet20_cifar10_32-64-4layer-60e-noisecoord-resmlpv2_smooth''}'
hyper_model:
  desc: null
  value: '{''input_dim'': 6, ''hidden_dim'': 512, ''num_layers'': 8, ''num_freqs'':
    32, ''output_dim'': 9, ''ema_decay'': 0.995, ''loss_weight'': {''ce_weight'':
    1.0, ''reg_weight'': 0.0001, ''recon_weight'': 1.0, ''kd_weight'': 0.1}, ''type'':
    ''resmlp''}'
dimensions:
  desc: null
  value: '{''range'': [32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
    47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64], ''test'':
    32, ''norm'': 64, ''start'': 64}'
base_config:
  desc: null
  value: /homes/tsommariva/neumeta/neumeta/config/base_config.yaml
config:
  desc: null
  value: /homes/tsommariva/neumeta/neumeta/config/cifar10/resnet20_cifar10_32-64v3_200e-coordnoise-resmlpv2_smooth.yaml
ratio:
  desc: null
  value: 1.0
resume_from:
  desc: null
  value: null
load_from:
  desc: null
  value: null
test_result_path:
  desc: null
  value: null
test:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.12.7
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1732014173.0
    t:
      1:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      2:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      3:
      - 13
      - 16
      - 23
      - 61
      4: 3.12.7
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
